//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayStation.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Race()
        {
            this.Timetables = new HashSet<Timetable>();
        }
    
        public int id { get; set; }
        public int destination { get; set; }
        public int numberOfSeatsClass1 { get; set; }
        public int numberOfSeatsClass2 { get; set; }
        public int numberOfSeatsClass3 { get; set; }
        public double priceClass1 { get; set; }
        public double priceClass2 { get; set; }
        public double priceClass3 { get; set; }
    
        public virtual Destination Destination1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timetable> Timetables { get; set; }
    }
}
